# Generated by Django 5.0.4 on 2024-06-26 16:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("AIApp", "0004_userdescription_interaction_style"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userdescription",
            unique_together={("uid", "projectid", "botid")},
        ),
    ]
