# Generated by Django 5.0.4 on 2024-06-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AIApp", "0002_userdescription_url_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdescription",
            name="url_data",
            field=models.JSONField(null=True),
        ),
    ]
