# Generated by Django 5.0.4 on 2024-06-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AIApp", "0003_alter_userdescription_url_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdescription",
            name="interaction_style",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
