# Generated by Django 5.0.4 on 2024-06-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AIApp", "0005_alter_userdescription_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdescription",
            name="history_list",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
