# Generated by Django 5.0.4 on 2024-06-27 09:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("AIApp", "0007_userdescription_train_status"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userdescription",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="userdescription",
            name="projectid",
        ),
        migrations.RemoveField(
            model_name="userdescription",
            name="uid",
        ),
    ]
