# Generated by Django 5.0.4 on 2024-07-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AIApp", "0008_alter_userdescription_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdescription",
            name="interaction_style",
            field=models.CharField(default="polite", max_length=50, null=True),
        ),
    ]
