# Generated by Django 5.0.4 on 2024-07-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AIApp", "0009_alter_userdescription_interaction_style"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdescription",
            name="botid",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
